/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author banyu
 */
public class Data extends javax.swing.JFrame {

    /**
     * Creates new form Data
     */
    public Data() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PemasukanTable = new javax.swing.JTable();
        PemasukanKembaliButton = new javax.swing.JButton();
        OKPemasukanButton = new javax.swing.JButton();
        PemasukanCariBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        PengeluaranKembaliButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PengeluaranTable = new javax.swing.JTable();
        PengeluaranCariBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        OKPengeluaranButton = new javax.swing.JButton();
        JenisField1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Laporan Berdasarkan");

        PemasukanTable.setAutoCreateRowSorter(true);
        PemasukanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Laporan", "Jenis Laporan", "Nominal", "Tanggal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PemasukanTable.setEnabled(false);
        jScrollPane1.setViewportView(PemasukanTable);

        PemasukanKembaliButton.setText("Kembali");

        OKPemasukanButton.setText("OK");

        PemasukanCariBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "SPP", "Yayasan", "Telkom" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PemasukanKembaliButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(PemasukanCariBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(OKPemasukanButton)
                        .addGap(5, 5, 5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(OKPemasukanButton)
                    .addComponent(PemasukanCariBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PemasukanKembaliButton))
        );

        jTabbedPane2.addTab("Pemasukan", jPanel1);

        PengeluaranKembaliButton.setText("Kembali");

        PengeluaranTable.setAutoCreateRowSorter(true);
        PengeluaranTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Laporan", "Jenis Laporan", "Nominal", "Tanggal"
            }
        ));
        PengeluaranTable.setEnabled(false);
        jScrollPane2.setViewportView(PengeluaranTable);

        PengeluaranCariBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Gaji", "Infrastruktur", "Beasiswa", "Logistik" }));

        jLabel2.setText("Cari Berdasarkan");

        OKPengeluaranButton.setText("OK");

        JenisField1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gaji", "Infrastruktur", "Beasiswa", "Logistik" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(PengeluaranKembaliButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(PengeluaranCariBox, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(OKPengeluaranButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JenisField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PengeluaranCariBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OKPengeluaranButton))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PengeluaranKembaliButton))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JenisField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Pengeluaran", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JenisField1;
    private javax.swing.JButton OKPemasukanButton;
    private javax.swing.JButton OKPengeluaranButton;
    private javax.swing.JComboBox<String> PemasukanCariBox;
    private javax.swing.JButton PemasukanKembaliButton;
    private javax.swing.JTable PemasukanTable;
    private javax.swing.JComboBox<String> PengeluaranCariBox;
    private javax.swing.JButton PengeluaranKembaliButton;
    private javax.swing.JTable PengeluaranTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables

    public void setActionListener(ActionListener a){
        PemasukanKembaliButton.addActionListener(a);
        PengeluaranKembaliButton.addActionListener(a);
        OKPemasukanButton.addActionListener(a);
        OKPengeluaranButton.addActionListener(a);
    }

    public JButton getOKPemasukanButton() {
        return OKPemasukanButton;
    }
    public JButton getOKPengeluaranButton() {
        return OKPengeluaranButton;
    }
    public JButton getPemasukanKembaliButton() {
        return PemasukanKembaliButton;
    }

    public JButton getPengeluaranKembaliButton() {
        return PengeluaranKembaliButton;
    }

    public void setPemasukanTable(Object[][] a,Object[] b ) {
        this.PemasukanTable.setModel(new DefaultTableModel(a, b){
        public boolean isCellEditable(int row,int column){
            return false;
        }
        });
    }

    public void setPengeluaranTable(Object[][] a,Object[] b ) {
        this.PengeluaranTable.setModel(new DefaultTableModel(a, b){
        public boolean isCellEditable(int row,int column){
            return false;
        }
        });
    }

    public String getPemasukanCariBox() {
        return PemasukanCariBox.getItemAt(PemasukanCariBox.getSelectedIndex());
    }

    public String getPengeluaranCariBox() {
        return PengeluaranCariBox.getItemAt(PengeluaranCariBox.getSelectedIndex());
    }
    
}
