/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author banyu
 */
public class InputDataPemasukan extends javax.swing.JFrame {

    public InputDataPemasukan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JenisField = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JumlahField = new javax.swing.JTextField();
        BatalButton = new javax.swing.JButton();
        SimpanButton = new javax.swing.JButton();
        TanggalField = new org.jdesktop.swingx.JXDatePicker();
        IDBankBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Input Data Pemasukan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Tanggal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Jenis Pemasukan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 164, -1, -1));

        JenisField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SPP", "Yayasan", "Telkom" }));
        getContentPane().add(JenisField, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 161, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("ID Bank");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 204, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Jumlah");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 244, -1, -1));
        getContentPane().add(JumlahField, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 241, 508, -1));

        BatalButton.setText("Batal");
        getContentPane().add(BatalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 362, 75, -1));

        SimpanButton.setText("Simpan");
        getContentPane().add(SimpanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 362, -1, -1));
        getContentPane().add(TanggalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 119, 180, -1));

        getContentPane().add(IDBankBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 201, 180, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 702, 10));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatalButton;
    private javax.swing.JComboBox<String> IDBankBox;
    private javax.swing.JComboBox<String> JenisField;
    private javax.swing.JTextField JumlahField;
    private javax.swing.JButton SimpanButton;
    private org.jdesktop.swingx.JXDatePicker TanggalField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void setIDBankBox(String x){
        IDBankBox.addItem(x);
    }
    
    public void showMessage(String m) {
        JOptionPane.showMessageDialog(this, m);
    }

    public void setJumlahField(String JumlahField) {
        this.JumlahField.setText(JumlahField);
    }
    
    
    public JButton getBatalButton() {
        return BatalButton;
    }

    public String getIDBankField() {
        return IDBankBox.getItemAt(IDBankBox.getSelectedIndex());
    }

    public String getJenisField() {
        return JenisField.getItemAt(JenisField.getSelectedIndex());
    }

    public Double getJumlahField() {
        if (Double.parseDouble(JumlahField.getText())==0) {
            showMessage("Data Belum Terisi Lengkap");
        }
        return Double.parseDouble(JumlahField.getText());
    }

    public JButton getSimpanButton() {
        return SimpanButton;
    }

    public Date getTanggalField() {
        if (TanggalField.getDate()==null)
            showMessage("Data Belum Terisi Lengkap");
        return TanggalField.getDate();
    }

    public void setActionListener(ActionListener ae){
        BatalButton.addActionListener(ae);
        SimpanButton.addActionListener(ae);
    }
}
