/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author banyu
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        InputDataPemasukanButton = new javax.swing.JButton();
        InputDataPengeluaranButton = new javax.swing.JButton();
        LihatDataButton = new javax.swing.JButton();
        CetakLaporanButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Main Menu");

        InputDataPemasukanButton.setText("Input Data Pemasukan");

        InputDataPengeluaranButton.setText("Input Data Pengeluaran");

        LihatDataButton.setText("Lihat Data");

        CetakLaporanButton.setText("Cetak Laporan");

        LogoutButton.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(InputDataPemasukanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InputDataPengeluaranButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LihatDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CetakLaporanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(InputDataPemasukanButton)
                .addGap(18, 18, 18)
                .addComponent(InputDataPengeluaranButton)
                .addGap(18, 18, 18)
                .addComponent(LihatDataButton)
                .addGap(18, 18, 18)
                .addComponent(CetakLaporanButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void setActionListerner(ActionListener a){
        CetakLaporanButton.addActionListener(a);
        InputDataPemasukanButton.addActionListener(a);
        InputDataPengeluaranButton.addActionListener(a);
        LihatDataButton.addActionListener(a);
        LogoutButton.addActionListener(a);
    }

    public JButton getCetakLaporanButton() {
        return CetakLaporanButton;
    }

    public JButton getInputDataPemasukanButton() {
        return InputDataPemasukanButton;
    }

    public JButton getInputDataPengeluaranButton() {
        return InputDataPengeluaranButton;
    }

    public JButton getLihatDataButton() {
        return LihatDataButton;
    }

    public JButton getLogoutButton() {
        return LogoutButton;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CetakLaporanButton;
    private javax.swing.JButton InputDataPemasukanButton;
    private javax.swing.JButton InputDataPengeluaranButton;
    private javax.swing.JButton LihatDataButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
